# Required fields are `version` and `updates`
version: 2
updates:
  # Required fields are `package-ecosystem`, `directory`, and `schedule.interval`

  # Maintain dependencies for NUsight2
  # Package ecosystem for yarn is npm
  - package-ecosystem: npm
    directory: /nusight2
    labels:
      - "-Dependencies"
      - "P-NUsight2"
      - "G-DevTools"
    reviewers:
      - "NUbots/nusight"
    schedule:
      interval: "monthly" # Checks on the first day of each month

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "-Dependencies"
      - "G-DevOps-QA"
    # TODO: Add devops team as reviewers
    # reviewers:
    # - "NUbots/Devops or whatever the team is called"
    schedule:
      interval: "daily"
