# Mandatory fields are `version` and `updates`
version: 2
updates:
  # Package ecosystem for yarn is npm
  - package-ecosystem: npm
    directory: /nusight2
    commit-message:
      # include: "scope" tells it to add the names of the
      # upgraded deps to the name, after the prefix
      include: "scope"
      prefix: "NUsight2 Dependency Update:"
    labels:
      - "-Dependencies"
      - "P-NUsight2"
      - "G-DevTools"
    reviewers:
      - "NUbots/nusight"
