# Need sudo to use the puppet installs
sudo: required

# C++ code on trusty
language: cpp
os: linux
dist: trusty

# Most modern travis image
group: edge

# Cache our toolchain directory to speed up the build
# This dir will get symlinked into place later
cache:
  directories:
    - toolchain

# Only do branch builds on master
branches:
  only:
    - 'master'

# Setup using puppet
before_install:
  # Make a symlink from our toolchain cache to /nubots
  - sudo ln -s $TRAVIS_BUILD_DIR/toolchain /nubots

  # Setup ruby and get the latest version of puppet
  - rvm install ruby --latest
  - sudo wget -N http://apt.puppetlabs.com/puppetlabs-release-trusty.deb -O $TRAVIS_BUILD_DIR/toolchain/puppetlabs-release-trusty.deb
  - sudo dpkg -i $TRAVIS_BUILD_DIR/toolchain/puppetlabs-release-trusty.deb
  - sudo apt-get update
  - sudo apt-get install puppet

  # Install the puppet modules that are required for this install
  - sudo mkdir -p /etc/puppet/modules;
  - sudo puppet module install puppetlabs-apt --module_repository https://forge.puppet.com --version 2.4.0
  - sudo puppet module install puppetlabs-vcsrepo --module_repository https://forge.puppet.com
  - sudo puppet module install camptocamp-archive --module_repository https://forge.puppet.com
  - sudo puppet module install maestrodev-wget --module_repository https://forge.puppet.com

install:
  # Apply the puppet file to the vm
  - sudo puppet apply --parser=future --verbose --debug --modulepath=puppet/modules:/etc/puppet/modules puppet/manifests/travis.pp

  # For some reason it looks like we have to run update-alternative again on travis
  - sudo update-alternatives --remove-all gcc || true
  - sudo update-alternatives --remove-all g++ || true
  - sudo update-alternatives --remove-all gfortan || true
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 100 --slave /usr/bin/g++ g++ /usr/bin/g++-7 --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-7

  # This is dumb... but otherwise we get weird errors
  # One day when travis supports 16.04 we can remove this
  - sudo wget -N https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test/+build/12615675/+files/libstdc++6_7.1.0-5ubuntu2~16.04_amd64.deb -O $TRAVIS_BUILD_DIR/toolchain/libstdc++6_7.1.0-5ubuntu2-16.04_amd64.deb
  - sudo dpkg -i $TRAVIS_BUILD_DIR/toolchain/libstdc++6_7.1.0-5ubuntu2-16.04_amd64.deb

script:
  - /usr/bin/python3 ./b platform select native
  - cd build
  - ninja
