# Need sudo to use the puppet installs
sudo: required

# C++ code on trusty
language: cpp
os: linux
dist: trusty

# Only do branch builds on master
branches:
  only:
    - 'master'

# Setup using puppet
before_install:
  - rvm install ruby --latest
  - wget http://apt.puppetlabs.com/puppetlabs-release-trusty.deb
  - sudo dpkg -i puppetlabs-release-trusty.deb
  - sudo apt-get update
  - sudo apt-get install puppet

  - sudo mkdir -p /etc/puppet/modules;
  - sudo puppet module install puppetlabs-apt --module_repository https://forge.puppet.com --version 2.4.0
  - sudo puppet module install puppetlabs-vcsrepo --module_repository https://forge.puppet.com
  - sudo puppet module install camptocamp-archive --module_repository https://forge.puppet.com
  - sudo puppet module install maestrodev-wget --module_repository https://forge.puppet.com

install:
  # Run some code to output some information for debugging
  - ls -lah /usr/bin

script:
  - sudo puppet apply --parser=future --verbose --debug --modulepath=puppet/modules:/etc/puppet/modules puppet/manifests/travis.pp
  - /usr/bin/python3 ./b platform select native
  - cd build
  - ninja
