# Need sudo to use the puppet installs
sudo: required

# C++ code on trusty
language: cpp
os: linux
dist: trusty

# Don't spam people with emails but do spam slack!
notifications:
  email: false
  slack:
    secure: BNNFwBsGwKxamyxH6OTtZLfOH9541zr3keNQ0U1rdE2eJpOL11h5gFCd2DHc4OhK596cHFmZrg6mryLXapqHEFCcrfx4CpLyJVxwXc/16rjE838sa4AoBV14ZzMoRiFsNdBOQOVBRu+0SR3kiJMRtJxOTPELnrHWOKmSuVGHjVg=

# Build for each of our platforms
env:
  - PLATFORM=native TYPE=build
  - PLATFORM=nuc7i7bnh TYPE=build
  - PLATFORM=fitpc2i TYPE=build
  - TYPE=format

# Most modern travis image
group: edge

# ccache makes things waaaaay faster
cache:
  ccache: true
  directories:
    # This cache is used for deb files so we don't smash nubots.net
    - toolchain

# Only do branch builds on master
branches:
  only:
    - 'master'

before_install:
  # If we are building get puppet
  - if [[ "$TYPE" == "build" ]]; then ./travis/get_puppet.sh; fi

install:
  # If we are building install the toolchain and apply puppet
  - if [[ "$TYPE" == "build" ]]; then .travis/get_toolchain.sh; fi
  - if [[ "$TYPE" == "build" ]]; then .travis/apply_puppet.sh; fi

  # If we are formatting, install clang-format
  - if [[ "$TYPE" == "format" ]]; then .travis/get_clang-format.sh; fi

script:
  # If we are building, run the build script and the test script
  - if [[ "$TYPE" == "build" ]]; then .travis/build_code.sh; fi
