# Need sudo to use the puppet installs
sudo: required

language: cpp
os: linux
dist: trusty

before_install:
  - sudo apt-get install puppet

script:
  - sudo puppet apply --modulepath=puppet/modules puppet/manifests/nubots.pp
  - ./b platform select native
  - cd build
  - ninja
