version: "3.2"
services:
  format:
    image: nubots:format
    build:
      context: docker
      dockerfile: format.Dockerfile
    volumes:
      - type: bind
        source: .
        target: /home/nubots/NUbots
        read_only: true
        consistency: cached
  nuc7i7bnh:
    image: nubots:nuc7i7bnh
    build:
      context: docker
      dockerfile: nubots.Dockerfile
      args:
        platform: nuc7i7bnh
    volumes:
      - type: bind
        source: .
        target: /home/nubots/NUbots
        read_only: true
        consistency: cached
      - type: volume
        source: nuc7i7bnh_build
        target: /home/nubots/NUbots/build
        consistency: delegated
  generic:
    image: nubots:generic
    build:
      context: docker
      dockerfile: nubots.Dockerfile
      args:
        platform: generic
    volumes:
      - type: bind
        source: .
        target: /home/nubots/NUbots
        read_only: true
        consistency: cached
      - type: volume
        source: generic_build
        target: /home/nubots/NUbots/build
        consistency: delegated
  native:
    image: nubots:native
    build:
      context: docker
      dockerfile: nubots.Dockerfile
      args:
        platform: native
    volumes:
      - type: bind
        source: .
        target: /home/nubots/NUbots
        read_only: true
        consistency: cached
      - type: volume
        source: native_build
        target: /home/nubots/NUbots/build
        consistency: delegated
volumes:
  native_build:
  nuc7i7bnh_build:
  generic_build:
