version: '3'
services:
  nuc7i7bnh:
    image: nubots:nuc7i7bnh
    build:
      context: docker
      dockerfile: Dockerfile
      args:
        platform: nuc7i7bnh
  generic:
    image: nubots:generic
    build:
      context: docker
      dockerfile: Dockerfile
