version: "3"
services:
  format:
    image: nubots:format
    build:
      context: docker
      dockerfile: format.Dockerfile
    volumes:
      - .:/home/nubots/NUbots
  nuc7i7bnh:
    image: nubots:nuc7i7bnh
    build:
      context: docker
      dockerfile: nubots.Dockerfile
      args:
        platform: nuc7i7bnh
    volumes:
      - .:/home/nubots/NUbots
      - ./build/nuc7i7bnh:/home/nubots/NUbots/build
  generic:
    image: nubots:generic
    build:
      context: docker
      dockerfile: nubots.Dockerfile
      args:
        platform: generic
    volumes:
      - .:/home/nubots/NUbots
      - ./build/generic:/home/nubots/NUbots/build
