# Global environment variables used for all steps
env:
  # These two environment variables are needed to make docker-compose use buildkit
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1

steps:
  # Push up new images to DockerHub when they get to master
  # Makes development faster as you can just pull the images rather than building them yourself
  # If you make modifications to the Dockerfile it should resume from the common point in master
  - label: "Push generic :docker: image"
    branches: master
    agents:
      dockerhub: true
    plugins:
      - docker-login#v2.0.1:
          username: nubotsdocker
          # Dockerhub password is loaded from the environment hook via DOCKER_LOGIN_PASSWORD environment variable
      - docker-compose#v3.1.0:
          config: .buildkite/NUbots/docker-compose.yml
          push:
            - generic:nubots/nubots:generic

  - label: "Push nuc7i7bnh :docker: image"
    branches: master
    agents:
      dockerhub: true
    plugins:
      - docker-login#v2.0.1:
          username: nubotsdocker
          # Dockerhub password is loaded from the environment hook via DOCKER_LOGIN_PASSWORD environment variable
      - docker-compose#v3.1.0:
          config: .buildkite/NUbots/docker-compose.yml
          push:
            - nuc7i7bnh:nubots/nubots:nuc7i7bnh

  - label: "Push nuc8i7beh :docker: image"
    branches: master
    agents:
      dockerhub: true
    plugins:
      - docker-login#v2.0.1:
          username: nubotsdocker
          # Dockerhub password is loaded from the environment hook via DOCKER_LOGIN_PASSWORD environment variable
      - docker-compose#v3.1.0:
          config: .buildkite/NUbots/docker-compose.yml
          push:
            - nuc8i7beh:nubots/nubots:nuc8i7beh

  # Wait to finish uploading the image before doing the next steps
  - wait

  # Build generic target and test
  - label: "Build generic and Test"
    command: "./b configure -- -DBUILD_TESTS=ON && ./b build && ./b tests run"
    plugins:
      - docker-compose#v3.0.3:
          config: .buildkite/NUbots/docker-compose.yml
          pull: generic_image
          run: generic
          workdir: /home/nubots/NUbots/

  # Generate role with unused modules and build it
  - label: "Build unused modules"
    command:
    # Enable writing in the roles directory for the generated role
      - sudo chmod 777 roles
    # We have to configure twice. The first configuration generates the cmake cache for `./b unused`, then the next one
    # turns on the role which `./b unused -g` generates
      - ./b configure -- -DBUILD_TESTS=ON
      - ./b unused -g
      - ./b configure
      - ./b build

  # Build for both nuc targets
  - label: "Build nuc7i7bnh"
    command: echo "nuc7i7bnh image successfully built!"
    plugins:
      - docker-compose#v3.0.3:
          config: .buildkite/NUbots/docker-compose.yml
          pull: nuc7i7bnh_image
          run: nuc7i7bnh
          workdir: /home/nubots/NUbots/
  - label: "Build nuc8i7beh"
    command: echo "nuc8i7beh image successfully built!"
    plugins:
      - docker-compose#v3.0.3:
          config: .buildkite/NUbots/docker-compose.yml
          pull: nuc8i7beh_image
          run: nuc8i7beh
          workdir: /home/nubots/NUbots/

  # Build NUsight2
  - label: "Build NUsight2"
    command:
      - cd ./nusight2
      - yarn
      - yarn build:ci
    plugins:
      - ./.buildkite/NUsight2/plugins/cache: ~
      - docker#v3.5.0:
          image: "node:12"
          always-pull: true
          propagate-uid-gid: true
          environment:
            - "HOME=/workdir"

  - label: "Build NUsight2 Storybook"
    command:
      - cd ./nusight2
      - yarn
      - yarn storybook:build
    plugins:
      - ./.buildkite/NUsight2/plugins/cache: ~
      - docker#v3.5.0:
          image: "node:12"
          always-pull: true
          propagate-uid-gid: true
          environment:
            - "HOME=/workdir"

  # Test NUsight
  - label: "Test NUsight2"
    command:
      - cd ./nusight2
      - yarn
      - yarn test:ci
    plugins:
      - ./.buildkite/NUsight2/plugins/cache: ~
      - docker#v3.5.0:
          image: "node:12"
          always-pull: true
          propagate-uid-gid: true
          environment:
            - "HOME=/workdir"

  # Formatting
  - label: "Validate C++ and Protobuf formatting"
    command: ".buildkite/NUbots/scripts/validate_clang_format.sh"
    plugins:
      - docker-compose#v3.0.3:
          config: .buildkite/NUbots/docker-compose.yml
          pull: generic_image
          run: generic
          workdir: /home/nubots/NUbots/
  - label: "Validate CMake formatting"
    command: ".buildkite/NUbots/scripts/validate_cmake_format.sh"
    plugins:
      - docker-compose#v3.0.3:
          config: .buildkite/NUbots/docker-compose.yml
          pull: generic_image
          run: generic
          workdir: /home/nubots/NUbots/
  - label: "Validate Python formatting"
    command: ".buildkite/NUbots/scripts/validate_python_format.sh"
    plugins:
      - docker-compose#v3.0.3:
          config: .buildkite/NUbots/docker-compose.yml
          pull: generic_image
          run: generic
          workdir: /home/nubots/NUbots/
  - label: "Check NUsight code with eslint"
    command:
      - cd ./nusight2
      - yarn
      - yarn eslint
    plugins:
      - ./.buildkite/NUsight2/plugins/cache: ~
      - docker#v3.5.0:
          image: "node:12"
          always-pull: true
          propagate-uid-gid: true
          environment:
            - "HOME=/workdir"
