steps:
  - label: "Validate Clang Format"
    command: "/home/nubots/NUbots/.buildkite/scripts/validate_format.sh"
    plugins:
      - docker-compose#v3.0.3:
          build: clang-format
      - docker-compose#v3.0.3:
          run: clang-format
  - label: "Build for NUC"
    command: "/home/nubots/NUbots/.buildkite/scripts/build_code.sh"
    plugins:
      - docker-compose#v3.0.3:
          build: nuc7i7bnh
      - docker-compose#v3.0.3:
          run: nuc7i7bnh
