steps:
  # Push up new images to DockerHub when they get to master
  - label: ":docker: Push new images"
    agents:
      dockerhub: true
    plugins:
      - docker-login#v2.0.1:
          username: nubotsdocker
      - docker-compose#v3.1.0:
          push:
            - generic:index.docker.io/nubots/nubots:generic
            - nuc7i7bnh:index.docker.io/nubots/nubots:nuc7i7bnh
  # Build for the NUC
  - label: "Build for NUC"
    command: "./b configure -- -DBUILD_TESTS=ON && ./b build && ./b build test"
    plugins:
      - docker-compose#v3.0.3:
          config: .buildkite/docker-compose.yml
          run: nuc7i7bnh
          workdir: /home/nubots/NUbots/

  # Formatting
  - label: "Validate C++ and Protobuf formatting"
    command: ".buildkite/scripts/validate_clang_format.sh"
    plugins:
      - docker-compose#v3.0.3:
          config: .buildkite/docker-compose.yml
          run: generic
          workdir: /home/nubots/NUbots/
  - label: "Validate CMake formatting"
    command: ".buildkite/scripts/validate_cmake_format.sh"
    plugins:
      - docker-compose#v3.0.3:
          config: .buildkite/docker-compose.yml
          run: generic
          workdir: /home/nubots/NUbots/
  - label: "Validate Python formatting"
    command: ".buildkite/scripts/validate_python_format.sh"
    plugins:
      - docker-compose#v3.0.3:
          config: .buildkite/docker-compose.yml
          run: generic
          workdir: /home/nubots/NUbots/
