steps:
  - label: "Validate Clang Format"
    command: ".buildkite/scripts/validate_format.sh"
    plugins:
      - docker-compose#v3.0.3:
          run: clang-format
          workdir: /home/nubots/NUbots/
  - label: "Build for NUC"
    command: ".buildkite/scripts/build_code.sh"
    plugins:
      - docker-compose#v3.0.3:
          run: nuc7i7bnh
          workdir: /home/nubots/NUbots/
