steps:
  # Build the docker images
  - label: "Build Docker Images"
    plugins:
      - docker-compose#v3.0.3:
          config: docker/docker-compose.yml
          build:
           - clang-format
           - nuc7i7bnh

  # Wait until they are built
  - wait

  - label: "Validate Clang Format"
    command: "/code/NUbots/.buildkite/scripts/validate_format.sh"
    plugins:
      - docker-compose#v3.0.3:
          config: docker/docker-compose.yml
          run: clang-format
  - label: "Build for NUC"
    command: "/code/NUbots/.buildkite/scripts/build_code.sh"
    plugins:
      - docker-compose#v3.0.3:
          config: docker/docker-compose.yml
          run: nuc7i7bnh
