version: '3'
services:
  vscode:
    # This stops the container from exiting so vscode can connect
    tty: true
    image: nubots:vscode
    build:
      context: ./../docker
      dockerfile: nubots.Dockerfile
      args:
        platform: generic
    volumes:
      - ./../:/home/nubots/NUbots
