# Reusable Workflow for building the Docker Image.
name: Build Part of Image

# Controls when the action will run.
on:
  # Triggers the workflow when it's referenced in another workflow.
  workflow_call:
    # Specify the inputs that need to be passed when calling this workflow.
    inputs:
      target:
        required: true
        type: string
      cache_from:
        required: true
        type: string
    secrets:
      docker_hub_username:
        required: true
      docker_hub_password:
        required: true

jobs:
  # Build part of the docker image.
  build_docker:
    name: "Build docker image"

    # The type of runner that the job will run on.
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v2

      # Setup docker buildx
      - name: 🐳 Set up docker buildx 🐳
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.docker_hub_username }}
          password: ${{ secrets.docker_hub_password }}

      # Build the docker image
      - name: 🐳 Build the docker image 🐳
        uses: docker/build-push-action@v2.7.0
        with:
          pull: true
          tags: "nubots/nubots:pull-request-${{ github.event.number }}-${{ inputs.target }}"
          file: docker/Dockerfile
          context: docker
          build-args: |
            platform=generic
            BUILDKIT_INLINE_CACHE=1
          target: ${{ inputs.target }}
          push: true
          cache-from: ${{ inputs.cache_from }}
