name: "Doxygen GitHub Pages Deploy Action"
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt-get install doxygen graphviz -y

      - name: Install and Build 🔧
        run: doxygen .Doxyfile

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: doc/Generated/html
